# Site Settings
theme: jekyll-theme-architect
title: Nicholas Dysle
description: My GitHub Pages Website!
baseurl: ''
url: https://ndysle1.github.io/

# Build Settings
show_downloads: <!["true" or "false" to indicate whether to provide a download URL]>
google_analytics: [UA-179473891-1]
include: ['_pages']
markdown: kramdown
input: GFM
gems:
  - jekyll-font-awesome-sass
font-awesome:
  assets: true
