# Site Settings
theme: jekyll-theme-architect
title: Nicholas Dysle
description: Nick Dysle's GitHub Pages
baseurl: ''
url: https://ndysle1.github.io/

# Build Settings
include: ['_pages']
markdown: kramdown
input: GFM
