# Site Settings
theme: jekyll-theme-architect
title: Nicholas Dysle
description: My GitHub Pages Website!
baseurl: ''
url: https://ndysle1.github.io/

# Build Settings
include: ['_pages']
markdown: kramdown
input: GFM
gems:
  - jekyll-font-awesome-sass
font-awesome:
  assets: true
